# Default values for pgmq-postgrest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: postgrest/postgrest
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v12.2.3

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}

securityContext: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: postgrest.docker.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /live
    port: health
readinessProbe:
  httpGet:
    path: /ready
    port: health

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Custom playground config

playground:
  postgrest:
    anonymousRole: &playgroundPostgrestAnonymousRole anonymous
    authenticatorRole: &playgroundPostgrestAuthenticatorRole authenticator
    extraEnvVars:
      - name: PGRST_LOG_LEVEL
        value: debug
    healthCheckPort: 4000
    jwtSecretKey: postgrest-jwt-secret
    loggedinRole: &playgroundPostgrestLoggedinRole loggedin
    schema: &playgroundPostgrestSchema postgrest
  secret:
    name: &playgroundSecretName playground-secret
    values:
      postgresPassword: ""
      password: ""
      replicationPassword: ""
      postgresHost: "" # Defaults to "<chart-name>-postgresql"
      postgresPort: "" # Defaults to "5432"
      postgrestJwtSecret: ""
      keycloakAdminPassword: ""
      keycloakPostgresUser: "" # Defaults to "keycloak"
      keycloakPostgresDatabase: "" # Defaults to "keycloak"
      keycloakPostgresPassword: ""

# Sub-charts

keycloak:
  auth:
    adminUser: kadmin
    existingSecret: *playgroundSecretName
    passwordSecretKey: keycloak-admin-password
  enabled: true
  extraEnvVars:
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
  externalDatabase:
    existingSecret: *playgroundSecretName
    existingSecretDatabaseKey: &keycloakExternalDatabaseExistingSecretDatabaseKey keycloak-postgres-database
    existingSecretHostKey: postgres-host
    existingSecretPasswordKey: &keycloakExternalDatabaseExistingSecretPasswordKey keycloak-postgres-password
    existingSecretPortKey: postgres-port
    existingSecretUserKey: &keycloakExternalDatabaseExistingSecretUserKey keycloak-postgres-user
  ingress:
    enabled: true
    labels:
      ingress.kubernetes.io/ssl-redirect: "false"
    hostname: keycloak.docker.localhost

  postgresql:
    enabled: false

minio:
  enabled: false

rabbitmq:
  enabled: false

postgresql:
  auth:
    database: postgres
    existingSecret: *playgroundSecretName
    secretKeys:
      userPasswordKey: &postgresqlAuthSecretKeysUserPasswordKey password

  enabled: true
  image:
    debug: true
  #   registry: registry:5000
  #   repository: rotty3000/pgmq-bitnami
  #   tag: 1.5.0-pg17-deb12

  primary:
    extraEnvVars:
      - name: KC_DATABASE_DATABASE
        valueFrom:
          secretKeyRef:
            name: *playgroundSecretName
            key: *keycloakExternalDatabaseExistingSecretDatabaseKey
      - name: KC_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: *playgroundSecretName
            key: *keycloakExternalDatabaseExistingSecretPasswordKey
      - name: KC_DATABASE_ROLE
        valueFrom:
          secretKeyRef:
            name: *playgroundSecretName
            key: *keycloakExternalDatabaseExistingSecretUserKey
      - name: PGRST_ANONYMOUS_ROLE
        value: *playgroundPostgrestAnonymousRole
      - name: PGRST_AUTHENTICATOR_ROLE
        value: *playgroundPostgrestAuthenticatorRole
      - name: PGRST_AUTHENTICATOR_PASSWORD
        valueFrom:
          secretKeyRef:
            name: *playgroundSecretName
            key: *postgresqlAuthSecretKeysUserPasswordKey
      - name: PGRST_LOGGEDIN_ROLE
        value: *playgroundPostgrestLoggedinRole
      - name: PGRST_SCHEMA
        value: *playgroundPostgrestSchema
    initdb:
      scripts:
        00_init_keycloak.sh: |
          #!/bin/bash

          export PGPASSWORD=${POSTGRES_PASSWORD}
          psql -U ${POSTGRESQL_USERNAME} <<-END
            create role ${KC_DATABASE_ROLE} noinherit login password '${KC_DATABASE_PASSWORD}';
            create database ${KC_DATABASE_DATABASE} owner ${KC_DATABASE_ROLE} encoding 'UTF8';
          END
        01_init_postgrest.sh: |
          #!/bin/bash

          export PGPASSWORD=${POSTGRES_PASSWORD}
          psql -U ${POSTGRESQL_USERNAME} <<-END
            create role ${PGRST_AUTHENTICATOR_ROLE} noinherit login password '${PGRST_AUTHENTICATOR_PASSWORD}';
            create role ${PGRST_ANONYMOUS_ROLE} nologin;
            create role ${PGRST_LOGGEDIN_ROLE} nologin;
            grant ${PGRST_ANONYMOUS_ROLE} to ${PGRST_AUTHENTICATOR_ROLE};
            grant ${PGRST_LOGGEDIN_ROLE} to ${PGRST_AUTHENTICATOR_ROLE};
            grant ${POSTGRESQL_USERNAME} to ${PGRST_LOGGEDIN_ROLE};

            create schema ${PGRST_SCHEMA};
            grant usage on schema ${PGRST_SCHEMA} to ${PGRST_ANONYMOUS_ROLE};
            grant usage on schema ${PGRST_SCHEMA} to ${PGRST_LOGGEDIN_ROLE};

            NOTIFY pgrst, 'reload schema';
          END
