# Default values for pgmq-postgrest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: postgrest/postgrest
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v12.2.3

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}

securityContext: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: postgrest.docker.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /live
    port: health
readinessProbe:
  httpGet:
    path: /ready
    port: health

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Custom playground config

playground:
  postgrest:
    anonymousRole: anonymous
    authenticatorRole: authenticator
    extraEnvVars:
      - name: PGRST_LOG_LEVEL
        value: debug
    healthCheckPort: 4000
    jwtSecretKey: postgrest-jwt-secret
    loggedinRole: loggedin
    schema: postgrest
  secret:
    createdManually: true
    name: playground-secret

# Sub-charts

keycloak:
  enabled: true
  externalDatabase:
    existingSecret: "{{ .Values.playground.secret.name }}"
    existingSecretDatabaseKey: '{{ .Release.Name }}-{{ default "postgresql" .Values.postgresql.nameOverride }}'
    existingSecretHostKey: postgres-host
    existingSecretPasswordKey: postgres-keycloak-password
    existingSecretPortKey: postgres-port
    existingSecretUserKey: postgres-keycloak-user
  ingress:
    enabled: true
    labels:
      ingress.kubernetes.io/ssl-redirect: "false"
    hostname: keycloak.docker.localhost

  postgresql:
    enabled: false

minio:
  enabled: false

rabbitmq:
  enabled: false

postgresql:
  auth:
    database: postgres
    existingSecret: "{{ .Values.playground.secret.name }}"
    secretKeys:
      userPasswordKey: password

  enabled: true
  image:
    debug: true
  #   registry: registry:5000
  #   repository: rotty3000/pgmq-bitnami
  #   tag: 1.5.0-pg17-deb12

  primary:
    extraEnvVars:
      - name: KC_DATABASE_DATABASE
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.playground.secret.name }}"
            key: "{{ .Values.keycloak.externalDatabase.existingSecretDatabaseKey }}"
      - name: KC_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.playground.secret.name }}"
            key: "{{ .Values.keycloak.externalDatabase.existingSecretPasswordKey }}"
      - name: KC_DATABASE_ROLE
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.playground.secret.name }}"
            key: "{{ .Values.keycloak.externalDatabase.existingSecretUserKey }}"
      - name: PGRST_AUTHENTICATOR_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "{{ .Values.playground.secret.name }}"
            key: "{{ .Values.postgresql.auth.secretKeys.userPasswordKey }}"
    initdb:
      scripts:
        00_init_keycloak.sh: |
          #!/bin/bash

          export PGPASSWORD=${POSTGRES_PASSWORD}
          psql -U ${POSTGRESQL_USERNAME} <<-END
            create role ${KC_DATABASE_ROLE} noinherit login password '${KC_DATABASE_PASSWORD}';
            create database ${KC_DATABASE_DATABASE} owner ${KC_DATABASE_ROLE} encoding 'UTF8';
          END
        01_init_postgrest.sh: |
          #!/bin/bash

          export PGPASSWORD=${POSTGRES_PASSWORD}
          psql -U ${POSTGRESQL_USERNAME} <<-END
            create role {{ .Values.playground.postgrest.authenticatorRole }} noinherit login password '${PGRST_AUTHENTICATOR_PASSWORD}';
            create role {{ .Values.playground.postgrest.anonymousRole }} nologin;
            create role {{ .Values.playground.postgrest.loggedinRole }} nologin;
            grant {{ .Values.playground.postgrest.anonymousRole }} to {{ .Values.playground.postgrest.authenticatorRole }};
            grant {{ .Values.playground.postgrest.loggedinRole }} to {{ .Values.playground.postgrest.authenticatorRole }};
            grant ${POSTGRESQL_USERNAME} to {{ .Values.playground.postgrest.loggedinRole }};

            create schema {{ .Values.playground.postgrest.schema }};
            grant usage on schema {{ .Values.playground.postgrest.schema }} to {{ .Values.playground.postgrest.anonymousRole }};
            grant usage on schema {{ .Values.playground.postgrest.schema }} to {{ .Values.playground.postgrest.loggedinRole }};

            NOTIFY pgrst, 'reload schema';
          END
