apiVersion: v1
kind: Pod
metadata:
  name: readonly-oci-volume-pod
spec:
  containers:
    - name: test
      image: registry.k8s.io/e2e-test-images/echoserver:2.3
      volumeMounts:
        - name: volume
          mountPath: /volume
  volumes:
    - name: volume
      image:
        reference: busybox:latest
        pullPolicy: IfNotPresent
