apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgmq-postgrest.fullname" . }}
  labels:
    {{- include "pgmq-postgrest.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pgmq-postgrest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pgmq-postgrest.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pgmq-postgrest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGDATABASE
              value: {{ default "postgres" .Values.postgresql.auth.database }}
            - name: PGHOST
              value: {{ .Release.Name }}-{{ default "postgresql" .Values.postgresql.nameOverride }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgmq-postgrest.secretName" . }}
                  key: {{ default "password" .Values.postgresql.auth.secretKeys.userPasswordKey }}
            - name: PGPORT
              value: {{ default "5432" .Values.postgresql.containerPorts.postgresql | quote }}
            - name: PGRST_ADMIN_SERVER_PORT
              value: {{ .Values.playground.postgrest.healthCheckPort | quote }}
            - name: PGRST_DB_ANON_ROLE
              value: {{ default "anonymous" .Values.playground.postgrest.anonymousRole }}
            - name: PGRST_DB_SCHEMAS
              value: {{ default "rest" .Values.playground.postgrest.schema }}
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "pgmq-postgrest.secretName" . }}
                  key: {{ default "postgrest-jwt-secret" .Values.playground.postgrest.jwtSecretKey }}
            - name: PGUSER
              value: {{ .Values.playground.postgrest.authenticatorRole }}
            {{- toYaml .Values.playground.postgrest.extraEnvVars | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.playground.postgrest.healthCheckPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
