{{- $secretName := default (include "pgmq-postgrest.fullname" .) .Values.playground.secret.name -}}
{{- if not (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "pgmq-postgrest.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.playground.secret.values.postgresPassword }}
  postgres-password: {{ .Values.playground.secret.values.postgresPassword | b64enc }}
  {{- else }}
  postgres-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.password }}
  password: {{ .Values.playground.secret.values.password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.replicationPassword }}
  replication-password: {{ .Values.playground.secret.values.replicationPassword | b64enc }}
  {{- else }}
  replication-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.postgresHost }}
  postgres-host: {{ .Values.playground.secret.values.postgresHost | b64enc }}
  {{- else }}
  postgres-host: {{ (print (include "pgmq-postgrest.fullname" .) "-postgresql") | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.postgresPort }}
  postgres-port: {{ .Values.playground.secret.values.postgresPort | b64enc }}
  {{- else }}
  postgres-port: {{ "5432" | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.postgrestJwtSecret }}
  postgrest-jwt-secret: {{ .Values.playground.secret.values.postgrestJwtSecret | b64enc }}
  {{- else }}
  postgrest-jwt-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.keycloakAdminPassword }}
  keycloak-admin-password: {{ .Values.playground.secret.values.keycloakAdminPassword | b64enc }}
  {{- else }}
  keycloak-admin-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.keycloakPostgresUser }}
  keycloak-postgres-user: {{ .Values.playground.secret.values.keycloakPostgresUser | b64enc }}
  {{- else }}
  keycloak-postgres-user: {{ "keycloak" | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.keycloakPostgresDatabase }}
  keycloak-postgres-database: {{ .Values.playground.secret.values.keycloakPostgresDatabase | b64enc }}
  {{- else }}
  keycloak-postgres-database: {{ "keycloak" | b64enc }}
  {{- end }}

  {{- if .Values.playground.secret.values.keycloakPostgresPassword }}
  keycloak-postgres-password: {{ .Values.playground.secret.values.keycloakPostgresPassword | b64enc }}
  {{- else }}
  keycloak-postgres-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}